baseURL = "https://oktomus.com/"
languageCode = "en-us"
title = "oktomus | computer graphics"
theme = "m10c-customized"
avatar = "static/avatar.jpg"
disableKinds = ["taxonomyTerm", "taxonomy", "section"]

[taxonomies]
    category = "categories"
    tag = "tags"

[params]
  author = "Kevin Masson"
  header = "oktomus"
  blogTitle = "Blog"

[[params.social]]
  name = "github"
  url = "https://github.com/oktomus"
  title = "Github"

[[params.social]]
  name = "twitter"
  url = "https://twitter.com/oktomus"
  title = "Twitter"

[[params.social]]
  name = "mail"
  url = "mailto:contact@oktomus.com"
  title = "contact@oktomus.com"

[markup.goldmark.renderer]
unsafe= true

[markup]
  [markup.highlight]
    codeFences = true
    guessSyntax = false
    hl_Lines = ""
    lineNoStart = 1
    lineNos = false
    lineNumbersInTable = true
    noClasses = true
    style = "native"
    tabWidth = 4
