# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-10 17:24
from __future__ import unicode_literals

from django.db import migrations, models
import post.models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_auto_20170810_1908'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='thumbnail',
            field=models.ImageField(blank=True, upload_to=post.models.post_thumbnail_path),
        ),
    ]
