# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-06 18:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Work',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('slug', models.SlugField(unique=True)),
                ('text', models.TextField()),
                ('status', models.CharField(choices=[('d', 'Draft'), ('p', 'Published'), ('w', 'Withdrawn')], max_length=1)),
                ('thumbnail', models.ImageField(upload_to='work/thumbnails/%Y/%m/')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('publish_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('edited_on', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
