# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-10 15:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion

def switch_to_post(apps, schema_editor):
    OldWork = apps.get_model('work', 'OldWork')
    NewWork = apps.get_model('work', 'NewWork')
    for work in OldWork.objects.all():
        new_post_work = NewWork.objects.create(
                title=work.title,
                slug=work.slug,
                text=work.text,
                status=work.status,
                thumbnail=work.thumbnail,
                created_on=work.created_on,
                edited_on=work.edited_on,
                publish_date=work.publish_date,
                )
        work.delete()

def switch_to_nopost(apps, schema_editor):
    OldWork = apps.get_model('work', 'OldWork')
    NewWork = apps.get_model('work', 'NewWork')

    for work in NewWork.objects.all():
        new_work = OldWork.objects.create(
                title=work.title,
                slug=work.slug,
                text=work.text,
                status=work.status,
                thumbnail=work.thumbnail,
                created_on=work.created_on,
                edited_on=work.edited_on,
                publish_date=work.publish_date,
                )
        work.delete()


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0001_initial'),
        ('work', '0002_auto_20170810_1630'),
    ]

    operations = [
        migrations.RenameModel('Work', 'OldWork'),
        migrations.CreateModel(
            name='NewWork',
            fields=[
                ('post_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='post.Post')),
            ],
            bases=('post.post',),
        ),
        migrations.RunPython(switch_to_post, switch_to_nopost),
        migrations.DeleteModel('OldWork'),
        migrations.RenameModel('NewWork', 'Work')
    ]
