# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-06 17:39
from __future__ import unicode_literals

from django.db import migrations
import markdownx.models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20170529_1514'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='text',
            field=markdownx.models.MarkdownxField(),
        ),
    ]
