# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-10 16:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20170606_1757'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='thumbnail',
            field=models.ImageField(blank=True, upload_to='blog/thumbnails/%Y/%m/'),
        ),
    ]
