# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-10 16:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_article_thumbnail'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='description',
            field=models.CharField(default="Description de l'article", max_length=500),
            preserve_default=False,
        ),
    ]
