# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-09 13:54
from __future__ import unicode_literals

import blog.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20170708_1913'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='description',
            field=blog.models.DescriptionField(max_length=500),
        ),
    ]
